apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec: 
  mode: "daemonset"
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  hostNetwork: true
  config: |
    extensions:
      health_check:
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679

    receivers:
      otlp:
        protocols:
          http:
          grpc:
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 4000
        send_batch_max_size: 4000
        
      memory_limiter:
        check_interval: 1s
        limit_mib: 4000
        spike_limit_mib: 800

    exporters:
      otlp:
        endpoint: "tempo.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
          
    service:
      extensions: [health_check,pprof,zpages]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
